### ISSUE TITLE
Expected training time

### ISSUE THREAD

**Issue by chenhsuanlin** [tomasjakab/imm#1]
Hi! I'd like to ask how long it would take to fully train a model on CelebA. The default number of iterations is 30M, so with batch size 50, it's equivalent to training almost 10,000 epochs, which is a lot! Is it really necessary to optimize for that long? Also, how much time did it take you to train your model?
Thanks in advance!

**Comment by ankush-me** [comment]
That is a placeholder number. 100k-150k iterations are usually enough.

**Comment by chenhsuanlin** [comment]
Thanks!
