### ISSUE TITLE
Can this work handle occlusion?

### ISSUE THREAD

**Issue by towardsautonomy** [tomasjakab/imm#15]
Hello, I first want to thank the authors for this work. I just wanted to check if and how can we use this work for occluded or partially out of frames objects?

**Comment by ankush-me** [comment]
@towardsautonomy  -- thanks for your message.  While the method always predicts a keypoint even if the object is occluded (fully / partially), i.e., it does not handle occlusions explicitly, however, looking at the underlying heatmaps (esp. their peakiness) can inform how confident the model is about the location prediction, i.e., for occluded objects/parts the heat maps should be spread out.  Hope this helps.
