### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by NolenChen** [tomasjakab/imm#2]
Thank you for your great work. I'm now studying your code, following are some questions I do not quite understand:
1) what is the workaround_channels in imm_model.py
2) what is loss_mask ?

**Comment by tomasjakab** [comment]
Thanks for your interest!
1. This is used as a workaround for models trained using an earlier version of the code. The code had a bug that defined more channels than it actually used.
2. loss_mask is used to discount the reconstruction loss in the regions of the warped image which lie outside the original image.

**Comment by NolenChen** [comment]
Thank you so much
