### ISSUE TITLE
Disentangling style and geometry

### ISSUE THREAD

**Issue by abcp4** [tomasjakab/imm#3]
There is some example code to see the Disentangling style and geometry, where one keeps the appearance of the source, but with the target geometry, as shown in the paper?

**Comment by tomasjakab** [comment]
Hi! This should be easy to do by adapting the Jupyter notebook `examples/visualize.ipynb`.

You just need to modify the dictionary on this line
`dataset = tf.data.Dataset.from_tensors({'image': images, 'future_image': images})`
The values of the keys `'image'` and  `'future_image'` should be the appearance and pose images respectively.

Then you need to change this line
`landmarks = session.run(tensors['gauss_yx'])`
to something like this
`reconstructed_images = session.run(tensors['future_im_pred'])`
This will give you reconstructed images that have the appearance from `'image'` images and pose from `'future_image'` images.

Hope this helps.

(I might also provide a full script for that at some point.)

**Comment by abcp4** [comment]
It works, thanks!

**Comment by tomasjakab** [comment]
Awesome!
