### ISSUE TITLE
Video Dataset

### ISSUE THREAD

**Issue by theRealSuperMario** [tomasjakab/imm#4]
Great paper.

I am wondering how to adapt the data loader for a video dataset.
My educated guess would be that I need to derive from `ImagePair` class and sample pairs of frames from the video.

If I understand correctly, the `TPSDataset` is only necessary for image datasets and not video datasets.

Is that correct?

Thank you very much in advance for any comment

**Comment by ankush-me** [comment]
Thank you. 

Correct, for videos you only need to sample a pair of frames and can derive from `ImagePair`. 
Yes, `TPSDataset` is for image datasets (to generate a "pair" by randomly warping images).
